name: Build Native Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build JAR using Gradle
        run: gradlew build

      - name: Install WiX Toolset
        run: choco install wix-toolset --no-progress

      - name: Create Windows Installer with jpackage
        run: |
          jpackage --input out/artifacts/Registermaschine_jar \
                   --name Registermaschine \
                   --main-jar Registermaschine.jar \
                   --main-class dk.tij.registermaschine.RegistermaschineLauncher \
                   --type exe \
                   --dest dist\windows

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build JAR using Gradle
        run: ./gradlew build

      - name: Create Linux Package with jpackage
        run: |
          jpackage --input out/artifacts/Registermaschine_jar \
                   --name Registermaschine \
                   --main-jar Registermaschine.jar \
                   --main-class dk.tij.registermaschine.RegistermaschineLauncher \
                   --type deb \
                   --dest dist/linux

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build JAR using Gradle
        run: ./gradlew build

      - name: Create macOS Package with jpackage
        run: |
          jpackage --input out/artifacts/Registermaschine_jar \
                   --name Registermaschine \
                   --main-jar Registermaschine.jar \
                   --main-class dk.tij.registermaschine.RegistermaschineLauncher \
                   --type app \
                   --dest dist/macos
