name: Build Windows, Linux, and macOS Installers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23'

      - name: Install Maven
        run: choco install maven --no-progress

      - name: Build JAR using Maven
        run: .\mvnw clean package -DskipTests

      - name: Install WiX Toolset
        run: choco install wixtoolset --no-progress

      - name: Create Windows Installer with jpackage
        run: jpackage --input out/artifacts/Registermaschine_jar --name Registermaschine --main-jar Registermaschine.jar --main-class dk.tij.registermaschine.RegistermaschineLauncher  --type app-image --dest ${{ github.workspace }}/dist/windows --jlink-options --bind-services --verbose

      - name: Upload Windows executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Registermaschine-exe
          path: ${{ github.workspace }}/dist/windows/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Build JAR using Maven
        run: ./mvnw clean package -DskipTests

      - name: Install jpackage dependencies
        run: sudo apt-get install -y default-jdk jpackage

      - name: Create Linux Installer with jpackage
        run: jpackage --input out/artifacts/Registermaschine_jar --name Registermaschine --main-jar Registermaschine.jar --main-class dk.tij.registermaschine.RegistermaschineLauncher  --type app-image --dest ${{ github.workspace }}/dist/linux --jlink-options --bind-services --verbose

      - name: Upload Linux executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Registermaschine-exe
          path: ${{ github.workspace }}/dist/linux/

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23'

      - name: Install Maven
        run: brew install maven

      - name: Build JAR using Maven
        run: ./mvnw clean package -DskipTests

      - name: Install jpackage dependencies
        run: brew install openjdk

      - name: Create macOS Installer with jpackage
        run: jpackage --input out/artifacts/Registermaschine_jar --name Registermaschine --main-jar Registermaschine.jar --main-class dk.tij.registermaschine.RegistermaschineLauncher  --type app-image --dest ${{ github.workspace }}/dist/mac --jlink-options --bind-services --verbose

      - name: Upload macOS executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Registermaschine-exe
          path: ${{ github.workspace }}/dist/mac/

