name: Build Native Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
  
      - name: Install Maven
        run: choco install maven --no-progress
  
      - name: Build JAR using Maven
        run: .\mvnw clean package -DskipTests
  
      - name: Install WiX Toolset
        run: choco install wixtoolset --no-progress
  
      - name: Create Windows Installer with jpackage
        run: jpackage --input out/artifacts/Registermaschine_jar --name Registermaschine --main-jar Registermaschine.jar --main-class dk.tij.registermaschine.RegistermaschineLauncher --type exe --dest dist/windows
      
      - name: Upload Windows executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Registermaschine-exe
          path: "%HOME%/dist/windows/"
